messenger4j:
  appSecret: "48cccf57b5ec4462f06b0595fba26889"
  verifyToken: "lasesisse"
  pageAccessToken: "EAAGlPfpWVvMBAMjJHU7YM9nCnIbAlcwaf7Prsp6k4TaCO3VG07V4Rn3naPuVf85YCY40HDvBz8JZAFt9LxlNZBgzgXfJSA9JnWgEOa8kgfuCe106Gj1i1odPvQcL2TJjxrBx8I89MuA7YraG8WUc6vj89iRNqnZBZCj9aKElPsTmZAg23rj8V2MDmWl4zd47DuJcpwPODdAZDZD"

logging:
  level:
    com:
      github:
        messenger4j: INFO

spring:
  data:
    rest:
      basePath: /api
  jpa.hibernate.ddl-auto: update
  jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    hikari:
      max-lifetime: 60000
    url: ${CLEARDB_DATABASE_URL}


  #local dbeaver:
 #   url: "jdbc:mysql://localhost:3306/autopood?createDatabaseIfNotExist=true&useSSL=false&useTimezone=true&serverTimezone=UTC"
 #   username: root
  #  password: Mangukoobas1

#   url: ${CLEARDB_DATABASE_URL}
# õige server heroku:
#    url: "jdbc:mysql://sql430.main-hosting.eu/u157943634_autopood?createDatabaseIfNotExist=true&useSSL=false&useTimezone=true&serverTimezone=UTC"
#    username: u157943634_autopood
#    password: uGusssdfj7F